---
title: "Shiny Project - Integrity Page"
author: "Henry Sun, Maxine Dobbs, and Miranda Yang"
date: "11/1/25"
format: pdf
editor: visual
---

# Data Sources

All data sources must be listed here with full citations. For websites, list the URL, as much information about the page as you can find, and extremely importantly, the date of access / download.

\newpage

# Practicing Academic Integrity

If your group worked with others (beyond your groupmates) or used resources outside of provided course material, such as Generative AI, (anything besides our textbook, course materials in the repo, labs, R help menu) to help complete this assignment, please acknowledge them below using a bulleted list. Remember that according to our class framework, if you engage with Generative AI tools, the tool and date of use must be listed here, and then a complete record of the chat history must be appended to the assignment.

<!-- ~~~~~~~~~~~~~~~~ YOU MAY BEGIN EDITING BELOW THIS LINE ~~~~~~~~~~~~~~~~ -->

*We acknowledge the following individuals with whom we worked on this assignment:*

-   Erika, a fellow student at Amherst College, helped us understand that the server and UI need to be in the same file.

*We used the following sources to help complete this assignment:*

-   Data sources from HMS downloaded on 10/8/25 to Google Drive: <https://drive.google.com/file/d/1HHy2IRv18xQVeYTIVuPmxtor8LV9sWwy/view?usp=drive_link.> (If you need access, contact Maxine at maxdobbs32\@gmail.com.)

    Full citation: Healthy Minds Network (2007-2025). Healthy Minds Study among Colleges and Universities, 2007-2025 datasets. Healthy Minds Network, University of Michigan, University of California Los Angeles, Boston University, and Wayne State University. <https://healthymindsnetwork.org/research/data-for-researchers.>

-   Guide on how to save datasets in order to reduce file reading time (10/24/25): <https://www.r-bloggers.com/2019/05/how-to-save-and-load-datasets-in-r-an-overview/>

-   Guide on how to read excel files (10/22/25): <https://www.geeksforgeeks.org/r-language/how-to-read-excel-file-in-r/>

-   Guide on how to read large csv files efficiently (10/20/25): <https://www.statology.org/how-to-handle-large-data-files-efficiently-in-r/>

-   Guide on how to use if_else with mutate (10/24/25): <https://dplyr.tidyverse.org/reference/if_else.html>

-   Guide on how to use case_when with mutate (10/24/25): <https://dplyr.tidyverse.org/reference/case_when.html>

-   Guide on how to turn NA values to 0 in a column (10/25/25): <https://stackoverflow.com/questions/13172711/replace-na-with-0-in-a-data-frame-column>

-   Guide on how to drop rows with NA values if they appear in a specific column (10/26/25): <https://www.geeksforgeeks.org/r-language/remove-rows-with-na-in-one-column-of-r-dataframe/>

-   Guide on ShinyApp (10/27/25): <https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/> (lessons start here), <https://shiny.posit.co/r/gallery/application-layout/navbar-example/>

-   Guide on leaflet in Shiny (10/27/25): <https://rstudio.github.io/leaflet/articles/shiny.html>

-   Guide on grouping multiple states in one (10/27/25): <https://stackoverflow.com/questions/76028013/outline-multiple-polygons-r-leaflet-to-show-territories>

-   Guide on merging several polygons on leaflet (10/28/25): <https://stackoverflow.com/questions/49354393/r-how-do-i-merge-polygon-features-in-a-shapefile-with-many-polygons-reproducib>

-   Guide on solving issue with inconsistent datum (10/28/25): <https://stackoverflow.com/questions/57223853/how-to-apply-spatial-polygons-to-leaflet-map-using-shp>

-   Guide on adding line breaks to Shinyapp (10/28/25): <https://stackoverflow.com/questions/47062446/helptext-shown-with-extra-lines-r-shiny>

-   Guide on implementing menu in Shiny (10/28/25): <https://shiny.posit.co/r/reference/shiny/1.6.0/selectinput.html>

-   Color palette (10/29/25): <https://colorbrewer2.org/#type=sequential&scheme=RdPu&n=3>

-   Rounding decimals on leaflet popup (10/30/25): <https://stackoverflow.com/questions/73229185/forcing-visualizations-in-r-to-have-only-2-decimal-points>

-   Remove NA from legend (10/30/25): <https://stackoverflow.com/questions/66663946/how-do-you-exclude-na-values-from-leaflet-legend>

-   Guide on static text on Shiny (10/30/25): <https://stackoverflow.com/questions/52544228/r-shiny-display-static-text-outside-sidebar-panel>

-   Guide on using plotly in Shiny to show information when the mouse hovers over points <https://shiny.posit.co/r/components/outputs/plot-plotly/#relevant-functions>

-   Stack Overflow article on how to use plotly <https://stackoverflow.com/questions/60294046/how-to-use-plotly-in-r-shiny>

-   Guide on dodge2 for bar graphs (11/1/25): <https://ggplot2.tidyverse.org/reference/position_dodge.html>

-   Stack Overflow article on how to rename legend labels (11/1/25): <https://stackoverflow.com/questions/55528008/how-to-rename-a-legend-item-in-ggplot>

-   Adding static images (11/1/25): <https://educationshinyappteam.github.io/Style_Guide/staticImages.html>

-   Shiny themes (11/1/25): <https://rstudio.github.io/shinythemes/>

-   Stack Overflow article on how to concatenate strings (11/1/25): <https://stackoverflow.com/questions/7201341/how-can-two-strings-be-concatenated>
